AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'test/integration/**/controls/**/*.rb'
    - 'test/unit/mock/profiles/**/*.rb'
    - 'test/unit/mock/config_dirs/**/*.rb'
    - 'lib/plugins/inspec-init/templates/plugins/inspec-plugin-template/**/*'
    - 'examples/**/controls/*.rb'
    - 'vendor/bundle/**/*'
Naming/FileName:
  Exclude:
    - 'lib/plugins/*-reporter/lib/**/*'
Metrics/AbcSize:
  Exclude:
    - 'lib/plugins/*-reporter/lib/**/*'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/plugins/*-reporter/lib/**/*'
Style/ClassVars:
  Exclude:
    - 'lib/inspec/reporter_registry.rb'
